# DEV Profile Configuration
server.port=8083

# Database DEV (Live sandbox)
spring.datasource.url=jdbc:postgresql://localhost:5432/fta
spring.datasource.username=postgres
spring.datasource.password=Alexsi02153013

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.football.backend=DEBUG
